### ISSUE TITLE
token の失効期限の管理

### ISSUE THREAD

**Issue by c-bata** [naritotakizawa/django-easy-regist#8]
Githubでお見かけしたので実装が気になって読んでみました。ありがとうございます、面白かったです。
1点気になったのは `default_token_generator` はその実装上、アクティベーションリンクの失効期限をコントロールできないかなと思っているのですがいかがでしょうか？

Djangoで似たようなライブラリだと django-registration-redux あたりが人気があるかと思いますが、そちらは `django.core.signing` の `dumps` と `load` を使っていて、settings.py で設定したリンクの有効期限内にあるかどうかをloadの際にチェックしています。

P.S. あと既にお気づきかもしれませんが、 `regist` は `register` の誤りかと思います

**Comment by naritotakizawa** [comment]
わざわざありがとうございます。
おっしゃるとおり失効期限のコントロールができません。`PASSWORD_RESET_TIMEOUT_DAYS`で一応設定できますが、そうするとパスワードリセットの失効期限に問題が出てきます。

リポジトリを公開にしたまま放ったらかしで申し訳ないのですが、ご指摘のとおり名前がアレだったり、全体的な見直しのため、少し前に[こちら](https://github.com/naritotakizawa/django-register-sample)で作り直しています(こちらのアクティベーションリンクは更に杜撰なので、そのうち修正すると思います)。

**Comment by c-bata** [comment]
replyありがとうございます。自分の認識が確認ができてよかったです。

実は django-register-sample のコードを読んでいて少し処理としては致命的な脆弱性の疑いのあるコードを見つけました。もし可動しているシステムがあれば、ここに内容を書くわけにはいかないので、githubにプロフィールに登録してあるメールに送ろうかなと思っていたのですが、いかがでしょうか (稼働しているシステムはございますか)？

**Comment by naritotakizawa** [comment]
稼働しているシステムはないので、こちらでも大丈夫ですが、メールでも大丈夫です。

**Comment by c-bata** [comment]
あ、すみません。こちら仕様を少し勘違いしました。
アクティベーションリンクを踏んだユーザーはログインユーザーとして扱うのではなく、もう一度ログインし直す仕様なんですね。よく実装を読むと懸念していた脆弱性はありませんでした。

アカウントを乗っ取られる危険性はありませんが、所持していないメールアドレスで大量にアカウントを作れてしまうように見えるので共有しておきます。

default_token_generator や django-registrationが利用している django.core.signing は、アクティベーションリンク内のコード生成に hmac によるハッシュ計算を行っています。hmacですのでアルゴリズムの指定だけでなくハッシュ化の際に message を指定する必要があるのですが、これには `settings.SECRET_KEY` が利用されているため攻撃者はこのSECRET_KEYを知らない限りアクティベーションリンクを予測することができません。

一方でこちらの実装は user.pk と user.email さえ分かれば後はurlsafe base64 encodeするだけでアクティベーションリンクが生成できてしまいます。暗号化の処理が含まれていないかと思います。つまり所持していないメールアドレスを利用して会員登録を行い、メールを受け取らずとも pk を順に変えながらアクティベーションリンクを生成してリクエストを送ればアカウント作成に成功してしまいます。pkがuuidとかであればまだ予測が難しくなりますが多くのユーザーは autoincrement な IntegerField かと思いますのでこれを予想するのはそれほど難しくありません。

ご参考までに

**Comment by naritotakizawa** [comment]
詳細な説明ありがとうございます。
アクティベーションリンクの作成処理を修正します。

**Comment by c-bata** [comment]
いいですね、基本的なアプローチは問題ないと思います。
少し気になったのは、期限切れやBadSignatureはNot Foundではなく、BadRequestとするのがHTTPのステータスとして正しいかと思います。

感想ありがとうございます。はい、PyCon JPにもDjangoネタでプロポーザルを出してみようかと思います。
